apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: marketing
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: marketing
    spec:
      containers:
      - name: marketing
        image: marketing
        ports:
        - containerPort: 3001
